
# * Products api tests

# ? Works
GET http://localhost:3000/api/product/all

###
# ? works
GET http://localhost:3000/api/product/1722444884668

###
# ? works

POST http://localhost:3000/api/create-product
Content-Type:application/json

{
    "prodName":"omil fragnace",
    "description":"powerfull wood perfume/cologne",
    "price":345.00,
    "quantity":40,
    "color":"black",
    "size":"45",
    "categoryId":"4",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTffmZUpuBxXWqra3KJbxV_tifTW0ItuxuhTw&s"
}

###
# ? works

DELETE http://localhost:3000/api/delete/1722444884668

###
# ? works

PUT http://localhost:3000/api/update/1722444884668
Content-Type:application/json

{
    "prodName":"bevy perfumes",
    "description":"nice matte perfume/cologne",
    "price":205.00,
    "quantity":40,
    "color":"white",
    "size":"45",
    "categoryId":"4",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTffmZUpuBxXWqra3KJbxV_tifTW0ItuxuhTw&s"
}


###
# * orders api tests

# ? works
POST http://localhost:3000/api/order/create-order
Content-Type:application/json

{
  "id": "order12345",
  "userId": "64c8fb9e4f50f32e6c3a5b89",
  "shopId": "64c8fc1a4f50f32e6c3a5b8a",
  "products": [
    "64c8fc8e4f50f32e6c3a5b8b",
    "64c8fca34f50f32e6c3a5b8c"
  ],
  "totalPrice": 1500,
  "paymentMethod": "M-pesa",
  "shippingAddress": "1234 Nairobi St, Nairobi, Kenya",
  "orderStatus": true
}

###
# ? works
GET http://localhost:3000/api/order/all

###
# ? works
GET http://localhost:3000/api/order/1722506179491

###
# ? works
GET http://localhost:3000/api/order/user/64c8fb9e4f50f32e6c3a5b89

###
# ? works
DELETE http://localhost:3000/api/order/delete/1722506179491

###
# * Category api tests
# ? works
POST http://localhost:3000/api/category/create
Content-Type:application/json

{
    "name":"Clothes",
    "description":"this is a new clothes category."
}

###
# ? works
DELETE http://localhost:3000/api/category/delete/1722510419489


###
# ? works
GET http://localhost:3000/api/category/all

###
# ? works
GET http://localhost:3000/api/category/1722510844605


# * shop api tests
###
# ? works
POST http://localhost:3000/api/shop/create
Content-Type: application/json

{
  "id": "shop12345",
  "userId": "60d5f9c55b4c1e2a10b5b10a",
  "shopName": "Tech Gadgets Store",
  "shopCategory": "60d5f9c55b4c1e2a10b5b10b",
  "products": [
    "60d5f9c55b4c1e2a10b5b10c",
    "60d5f9c55b4c1e2a10b5b10d"
  ],
  "paymentMethod": "M-pesa",
  "shopDescription": "A store that offers the latest tech gadgets and accessories."
}

###
# ? works
DELETE http://localhost:3000/api/shop/delete/1722513282784

###
# ? works
GET http://localhost:3000/api/shop/all

###
# ?works
GET http://localhost:3000/api/shop/1722513839458

###
# ? works
GET http://localhost:3000/api/shop/user/60d5f9c55b4c1e2a10b5b10a

###
# ? works
POST http://localhost:3000/api/payment/stk-push
Content-Type: application/json

{
   "amount": 1,
  "phone": "2547xxxxxxxx",
  "Order_ID": "123456"
}

###
POST http://localhost:3000/api/payment/stk-push-callback/123456
# ! issue: interchanged key and secret in .env, using .then in axios


# routes depend on controllers
# controller depends on use case
# use case depend on repo, entity
# repo depends on database

# entity>use case>models>create repo interfaces>implement repo>controllers>routes>db connection>entrypoint(index.js)

# TODO : update shop func, aggregation pipelines


###
# ? works
POST http://localhost:3000/api/payment/confirmPayment/ws_CO_02082024123006999719520494

###
# * users api tests
POST http://localhost:3000/api/user/sign-up
Content-Type: application/json

{
      "username": "Jane pette",
      "email": "jane@gmail.com",
      "image": "jane's image",
      "password": "jane@1234",
      "role": "seller"
}

###
POST http://localhost:3000/api/user/sign-in
Content-Type: application/json

{
  "email": "jane@gmail.com",
  "password": "jane@1234"
}

###
GET http://localhost:3000/api/user/66b8adeddd968cf3bfc0f278

###
PUT http://localhost:3000/api/user/update/66b8a34da06c90b91bc729dc
Content-Type: application/json

{
  "username":"kelly limo",
  "role":"buyer"
}

###
DELETE http://localhost:3000/api/user/delete/66b8a34da06c90b91bc729dc

###
GET http://localhost:3000/try
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmI4YWRlZGRkOTY4Y2YzYmZjMGYyNzgiLCJpYXQiOjE3MjMzODAzNjQsImV4cCI6MTcyMzM4MDM4NH0.JxjKg6iEs1esy-jIn-alGEHWv4tIrBDGdvGrUaD1MnM